export interface Medication {
  category: string;
  name: string;
  unit: string;
  purchasePrice: string;
  nafqaPrice: string;
  ahalyPrice: string;
}

export const medications: Medication[] = [
  // Section 1: أمبولات ومحاليل
  { category: "أمبولات ومحاليل", name: "ابيلوج ايبلوج 50 phenytoin epilog", unit: "امبول", purchasePrice: "6.30", nafqaPrice: "6.74", ahalyPrice: "7" },
  { category: "أمبولات ومحاليل", name: "اترابيسيلات 25 atrabesylate", unit: "امبول", purchasePrice: "12.18", nafqaPrice: "13.03", ahalyPrice: "22.5" },
  { category: "أمبولات ومحاليل", name: "ابراتروبيوم بروميد 250 اقبال ipratropium bromide", unit: "امبول", purchasePrice: "10.70", nafqaPrice: "11.45", ahalyPrice: "14.3" },
  { category: "أمبولات ومحاليل", name: "ابراتروبيوم بروميد 500 اقبال ipratropium bromide", unit: "امبول", purchasePrice: "6.64", nafqaPrice: "7.10", ahalyPrice: "8" },
  { category: "أمبولات ومحاليل", name: "اتروبين 1mg/1ml atropine", unit: "امبول", purchasePrice: "5.20", nafqaPrice: "5.56", ahalyPrice: "6.5" },
  { category: "أمبولات ومحاليل", name: "ادرينالين adrenaline 1gm", unit: "امبول", purchasePrice: "6.20", nafqaPrice: "6.63", ahalyPrice: "8.5" },
  { category: "أمبولات ومحاليل", name: "افدرين ephedrine", unit: "امبول", purchasePrice: "4.78", nafqaPrice: "5.11", ahalyPrice: "7" },
  { category: "أمبولات ومحاليل", name: "افزوليد linzolid 2mg/300ml", unit: "كيس", purchasePrice: "78.75", nafqaPrice: "84.26", ahalyPrice: "126" },
  { category: "أمبولات ومحاليل", name: "أكتترابيد بنفل مصري (أكتريابيد / Actrapid Penfill / Insulinagypt)", unit: "كربولة", purchasePrice: "50.40", nafqaPrice: "53.93", ahalyPrice: "60" },
  { category: "أمبولات ومحاليل", name: "اكترابيد اكتى رابيد فيال actrapid", unit: "فيال", purchasePrice: "105.00", nafqaPrice: "112.35", ahalyPrice: "120" },
  { category: "أمبولات ومحاليل", name: "أكتترابيد بنفل مستورد (أكتريابيد / Actrapid Penfill / Epidrea)", unit: "كربولة", purchasePrice: "112.88", nafqaPrice: "120.78", ahalyPrice: "190" },
  { category: "أمبولات ومحاليل", name: "البيومين human Albumin", unit: "فيال", purchasePrice: "1179.68", nafqaPrice: "1262.26", ahalyPrice: "1450" },
  { category: "أمبولات ومحاليل", name: "اوميز 40 نابيوزول", unit: "فيال", purchasePrice: "39.90", nafqaPrice: "42.69", ahalyPrice: "60" },
  { category: "أمبولات ومحاليل", name: "ايسوميبرازول 40 زوميجيرال", unit: "فيال", purchasePrice: "34.65", nafqaPrice: "37.08", ahalyPrice: "48" },
  { category: "أمبولات ومحاليل", name: "الفا كليندامايسين Alfaclindamycin دالاسين", unit: "امبول", purchasePrice: "26.25", nafqaPrice: "28.09", ahalyPrice: "40.5" },
  { category: "أمبولات ومحاليل", name: "امري كـ phytomenadione كوناكيون - ابيكافيت epicavit", unit: "امبول", purchasePrice: "3.73", nafqaPrice: "3.99", ahalyPrice: "8" },
  { category: "أمبولات ومحاليل", name: "اميكاسين 100", unit: "فيال", purchasePrice: "5.93", nafqaPrice: "6.35", ahalyPrice: "7.5" },
  { category: "أمبولات ومحاليل", name: "اميكاسين 500", unit: "فيال", purchasePrice: "12.86", nafqaPrice: "13.76", ahalyPrice: "34" },
  { category: "أمبولات ومحاليل", name: "امينوفلين aminophylline", unit: "امبول", purchasePrice: "4.50", nafqaPrice: "4.80", ahalyPrice: "6.00" },
  { category: "أمبولات ومحاليل", name: "امينوفين aminoven", unit: "زجاجة", purchasePrice: "151.94", nafqaPrice: "162.58", ahalyPrice: "200" },
  { category: "أمبولات ومحاليل", name: "اميودارون اميرون (كوردارون) amiodarone", unit: "امبول", purchasePrice: "6.30", nafqaPrice: "6.74", ahalyPrice: "7.5" },
  { category: "أمبولات ومحاليل", name: "انتودين 20", unit: "امبول", purchasePrice: "9.66", nafqaPrice: "10.34", ahalyPrice: "13" },
  { category: "أمبولات ومحاليل", name: "انسولين طويل المفعول فيال insulinagypt n", unit: "امبول", purchasePrice: "86.10", nafqaPrice: "92.13", ahalyPrice: "105" },
  { category: "أمبولات ومحاليل", name: "اوندانستيرون 8مجم/4مل دانست 8 مجم", unit: "امبول", purchasePrice: "8.93", nafqaPrice: "9.55", ahalyPrice: "45" },
  { category: "أمبولات ومحاليل", name: "اوندانستيرون 4مجم/2مل دانست 4 مجم", unit: "امبول", purchasePrice: "6.30", nafqaPrice: "6.74", ahalyPrice: "24" },
  { category: "أمبولات ومحاليل", name: "اوكسي توسين 10 مجم سينتوسين", unit: "امبول", purchasePrice: "7.35", nafqaPrice: "7.86", ahalyPrice: "12" },
  { category: "أمبولات ومحاليل", name: "اوكسي توسين 5 مجم", unit: "امبول", purchasePrice: "6.30", nafqaPrice: "6.74", ahalyPrice: "9" },
  { category: "أمبولات ومحاليل", name: "اومنيباك omnipaque", unit: "فيال", purchasePrice: "456.48", nafqaPrice: "488.43", ahalyPrice: "582" },
  { category: "أمبولات ومحاليل", name: "ايثاميسيلات دايسينون (Ethamsylate / Dicynone)", unit: "امبول", purchasePrice: "5.78", nafqaPrice: "6.18", ahalyPrice: "14" },
  { category: "أمبولات ومحاليل", name: "ايزوفلوران isoflurane", unit: "فيال", purchasePrice: "357.00", nafqaPrice: "381.99", ahalyPrice: "450" },
  { category: "أمبولات ومحاليل", name: "ايمتركس emetrex", unit: "امبول", purchasePrice: "0.00", nafqaPrice: "0.00", ahalyPrice: "0" },
  { category: "أمبولات ومحاليل", name: "امبينيم 500 تايينام imipenem", unit: "فيال", purchasePrice: "152.25", nafqaPrice: "162.91", ahalyPrice: "210" },
  { category: "أمبولات ومحاليل", name: "استيل سيستايين fluimucil", unit: "امبول", purchasePrice: "44.94", nafqaPrice: "48.09", ahalyPrice: "52.4" },
  { category: "أمبولات ومحاليل", name: "انتى ار اتش ruphalac", unit: "سرنجة", purchasePrice: "1630.00", nafqaPrice: "1744.10", ahalyPrice: "-" },
  { category: "أمبولات ومحاليل", name: "اميونوجلوبين 2.5 immunoglobulin ivig", unit: "سرنجة", purchasePrice: "6825.00", nafqaPrice: "7302.15", ahalyPrice: "-" },
  { category: "أمبولات ومحاليل", name: "ايتافيروز حديد", unit: "امبول", purchasePrice: "23.60", nafqaPrice: "25.26", ahalyPrice: "51" },
  { category: "أمبولات ومحاليل", name: "ايتافللين etaphylline", unit: "امبول", purchasePrice: "7.40", nafqaPrice: "7.92", ahalyPrice: "15" },
  { category: "أمبولات ومحاليل", name: "بيتغنين", unit: "امبول", purchasePrice: "7.40", nafqaPrice: "7.92", ahalyPrice: "15" },
  { category: "أمبولات ومحاليل", name: "بالميكورت 0.25", unit: "امبول", purchasePrice: "17.44", nafqaPrice: "18.66", ahalyPrice: "28.2" },
  { category: "أمبولات ومحاليل", name: "بالميكورت 0.5", unit: "امبول", purchasePrice: "23.22", nafqaPrice: "24.85", ahalyPrice: "37.6" },
  { category: "أمبولات ومحاليل", name: "بوديكسان 0.25", unit: "امبول", purchasePrice: "14.20", nafqaPrice: "15.19", ahalyPrice: "19.2" },
  { category: "أمبولات ومحاليل", name: "بوديكسان 0.5", unit: "امبول", purchasePrice: "18.97", nafqaPrice: "20.30", ahalyPrice: "26.45" },
  { category: "أمبولات ومحاليل", name: "بروبوفول 1% دبريفان diprivan", unit: "امبول", purchasePrice: "58.85", nafqaPrice: "62.97", ahalyPrice: "85" },
  { category: "أمبولات ومحاليل", name: "بانتوبرازول فيوتوبان بروتوفكس بانتولوك pantoprazole", unit: "فيال", purchasePrice: "34.65", nafqaPrice: "37.08", ahalyPrice: "59.5" },
  { category: "أمبولات ومحاليل", name: "بوتاسيوم كلورايد potassium chloride", unit: "امبول", purchasePrice: "3.99", nafqaPrice: "4.27", ahalyPrice: "5" },
  { category: "أمبولات ومحاليل", name: "بيتولفكس betolvex", unit: "امبول", purchasePrice: "15.65", nafqaPrice: "16.74", ahalyPrice: "32" },
  { category: "أمبولات ومحاليل", name: "بيرافين افيل", unit: "امبول", purchasePrice: "4.20", nafqaPrice: "4.49", ahalyPrice: "8" },
  { category: "أمبولات ومحاليل", name: "بيكربونات صوديوم sodium bicarbonate", unit: "امبول", purchasePrice: "10.94", nafqaPrice: "11.71", ahalyPrice: "14" },
  { category: "أمبولات ومحاليل", name: "باراسيتامول 1 جم انجكتمول بنادول برفلجان paracetamol", unit: "امبول", purchasePrice: "31.50", nafqaPrice: "33.71", ahalyPrice: "67" },
  { category: "أمبولات ومحاليل", name: "بي كوم b-com", unit: "امبول", purchasePrice: "3.87", nafqaPrice: "4.15", ahalyPrice: "8" },
  { category: "أمبولات ومحاليل", name: "الفيوفاكت 108 alveofact", unit: "فيال", purchasePrice: "8400.00", nafqaPrice: "8988.00", ahalyPrice: "-" },
  { category: "أمبولات ومحاليل", name: "الفيوفاكت 54 alveofact", unit: "فيال", purchasePrice: "5250.00", nafqaPrice: "5617.50", ahalyPrice: "-" },
  { category: "أمبولات ومحاليل", name: "بريزيدكس", unit: "امبول", purchasePrice: "231.00", nafqaPrice: "247.17", ahalyPrice: "295" },
  { category: "أمبولات ومحاليل", name: "بريماكور امبول (Primacor / Milrinone)", unit: "امبول", purchasePrice: "-", nafqaPrice: "1534.20", ahalyPrice: "-" },
  { category: "أمبولات ومحاليل", name: "تيرليبيسى كيبيليسى inadilvox leinoseiz تيراتام", unit: "امبول", purchasePrice: "14.70", nafqaPrice: "15.73", ahalyPrice: "29" },
  { category: "أمبولات ومحاليل", name: "تليبركس telebrix", unit: "فيال", purchasePrice: "392.70", nafqaPrice: "420.19", ahalyPrice: "425" },
  { category: "أمبولات ومحاليل", name: "تيتانوس توكسيد فيال tetanus toxoid", unit: "فيال", purchasePrice: "0.00", nafqaPrice: "0.00", ahalyPrice: "0" },
  { category: "أمبولات ومحاليل", name: "تيتانوس مصل امبول tetanus serum", unit: "فيال", purchasePrice: "0.00", nafqaPrice: "0.00", ahalyPrice: "0" },
  { category: "أمبولات ومحاليل", name: "تارجوسيد", unit: "فيال", purchasePrice: "320.16", nafqaPrice: "342.57", ahalyPrice: "408" },
  { category: "أمبولات ومحاليل", name: "تيجاسيل 50 مجم مستورد", unit: "فيال", purchasePrice: "577.00", nafqaPrice: "617.39", ahalyPrice: "839" },
  { category: "أمبولات ومحاليل", name: "تيجاسيل 50 مجم مصري", unit: "فيال", purchasePrice: "184.80", nafqaPrice: "197.74", ahalyPrice: "254" },
  { category: "أمبولات ومحاليل", name: "ثيوبنتال", unit: "فيال", purchasePrice: "49.35", nafqaPrice: "52.80", ahalyPrice: "65" },
  { category: "أمبولات ومحاليل", name: "جينتاميسين 80 جراميسين gentamicin", unit: "امبول", purchasePrice: "3.94", nafqaPrice: "4.21", ahalyPrice: "15" },
  { category: "أمبولات ومحاليل", name: "جاست ريج", unit: "امبول", purchasePrice: "6.73", nafqaPrice: "7.20", ahalyPrice: "9" },
  { category: "أمبولات ومحاليل", name: "جلسرايل تراينيترات (ترايديل / نيترونال) Tridil / Nitronal", unit: "امبول", purchasePrice: "37.80", nafqaPrice: "40.45", ahalyPrice: "51.5" },
  { category: "أمبولات ومحاليل", name: "دوبامين Dopamine", unit: "امبول", purchasePrice: "10.76", nafqaPrice: "11.52", ahalyPrice: "13" },
  { category: "أمبولات ومحاليل", name: "دوبوتامين (دوبتركس / Dobutrex)", unit: "امبول", purchasePrice: "29.40", nafqaPrice: "31.46", ahalyPrice: "35" },
  { category: "أمبولات ومحاليل", name: "ديبروفوس (ديكساجلوب / Diprofos)", unit: "امبول", purchasePrice: "13.65", nafqaPrice: "14.61", ahalyPrice: "33" },
  { category: "أمبولات ومحاليل", name: "ديكساميثازون dexamethasone", unit: "امبول", purchasePrice: "5.25", nafqaPrice: "5.62", ahalyPrice: "12" },
  { category: "أمبولات ومحاليل", name: "ديكلوفين diclofenac", unit: "امبول", purchasePrice: "3.68", nafqaPrice: "3.93", ahalyPrice: "7" },
  { category: "أمبولات ومحاليل", name: "ديكلوفين بوتاسيوم (Diclofenac Potassium)", unit: "امبول", purchasePrice: "7.59", nafqaPrice: "8.10", ahalyPrice: "12" },
  { category: "أمبولات ومحاليل", name: "سبازموفري (Spasmofree)", unit: "امبول", purchasePrice: "10.50", nafqaPrice: "11.24", ahalyPrice: "18" },
  { category: "أمبولات ومحاليل", name: "سيبروسيتام (نوتروبيل / Cerocetam)", unit: "امبول", purchasePrice: "7.35", nafqaPrice: "7.86", ahalyPrice: "9" },
  { category: "أمبولات ومحاليل", name: "ستربتوكينيز (سيدوناز / Sedonase)", unit: "فيال", purchasePrice: "1096.00", nafqaPrice: "1172.72", ahalyPrice: "2536" },
  { category: "أمبولات ومحاليل", name: "سيلستين كوتين", unit: "امبول", purchasePrice: "9.45", nafqaPrice: "10.11", ahalyPrice: "17.5" },
  { category: "أمبولات ومحاليل", name: "سيفوتاكسيم 1جم (Cefotaxime)", unit: "فيال", purchasePrice: "21.00", nafqaPrice: "22.47", ahalyPrice: "60" },
  { category: "أمبولات ومحاليل", name: "سيفترياكسون 1جم (إبيسفين / Epicephin / Ceftriaxone)", unit: "فيال", purchasePrice: "21.00", nafqaPrice: "22.47", ahalyPrice: "44" },
  { category: "أمبولات ومحاليل", name: "سيفوفلوران (عبوة) (Sevoflurane)", unit: "عبوة", purchasePrice: "2283.75", nafqaPrice: "2443.61", ahalyPrice: "2500" },
  { category: "أمبولات ومحاليل", name: "سيفيبيم 1جم (Cefepime)", unit: "امبول", purchasePrice: "52.45", nafqaPrice: "56.12", ahalyPrice: "73" },
  { category: "أمبولات ومحاليل", name: "سيربرولايسين (Cerebrolysin)", unit: "فيال", purchasePrice: "124.84", nafqaPrice: "133.58", ahalyPrice: "148" },
  { category: "أمبولات ومحاليل", name: "سيفوبيرازون 1جم (سيفوبيد / سيفوزون / بيراسيف / Cefoperazone / Cefobid)", unit: "فيال", purchasePrice: "23.10", nafqaPrice: "24.72", ahalyPrice: "29" },
  { category: "أمبولات ومحاليل", name: "سيفوبيرازون بلس / سيلباكتام (سيفوبيد بلس / سيفوزون بلس / سيفوزيد بلس / Cefobid Plus / Cefoperazone+Sulbactam)", unit: "فيال", purchasePrice: "34.65", nafqaPrice: "37.08", ahalyPrice: "77" },
  { category: "أمبولات ومحاليل", name: "سيفازولين 1جم (زينول / Cefazolin / Zinol)", unit: "فيال", purchasePrice: "34.65", nafqaPrice: "37.08", ahalyPrice: "48" },
  { category: "أمبولات ومحاليل", name: "سيفازولين 500مجم (Cefazolin 500mg)", unit: "فيال", purchasePrice: "19.95", nafqaPrice: "21.34", ahalyPrice: "31" },
  { category: "أمبولات ومحاليل", name: "سيفتازيديم 1جم (فورتام / Ceftazidime / Fortam)", unit: "فيال", purchasePrice: "28.35", nafqaPrice: "30.33", ahalyPrice: "53" },
  { category: "أمبولات ومحاليل", name: "سيفتازيديم 1جم مستورد (Ceftazidime Imported)", unit: "امبول", purchasePrice: "58.25", nafqaPrice: "62.33", ahalyPrice: "106" },
  { category: "أمبولات ومحاليل", name: "سيفوكسيتين 1جم (سيفوكسيتين / Cefoxitin 1g)", unit: "فيال", purchasePrice: "76.65", nafqaPrice: "82.00", ahalyPrice: "105" },
  { category: "أمبولات ومحاليل", name: "فورسيميد 20مجم لازيكس furosemide lasix", unit: "امبول", purchasePrice: "4.62", nafqaPrice: "4.94", ahalyPrice: "6.5" },
  { category: "أمبولات ومحاليل", name: "فورسيميد 40 مجم furosemide", unit: "امبول", purchasePrice: "6.30", nafqaPrice: "6.74", ahalyPrice: "7.5" },
  { category: "أمبولات ومحاليل", name: "فليبوتون", unit: "امبول", purchasePrice: "8.15", nafqaPrice: "8.72", ahalyPrice: "17" },
  { category: "أمبولات ومحاليل", name: "فلوكونازول 50مل ديفلوكان fluconazole diflucan", unit: "فيال", purchasePrice: "28.35", nafqaPrice: "30.33", ahalyPrice: "62" },
  { category: "أمبولات ومحاليل", name: "فلوكونازول 100مل ديفلوكان fluconazole diflucan", unit: "فيال", purchasePrice: "54.60", nafqaPrice: "58.42", ahalyPrice: "98" },
  { category: "أمبولات ومحاليل", name: "فانكومايسين 500 فانكوباكت vancomycin", unit: "فيال", purchasePrice: "52.50", nafqaPrice: "56.18", ahalyPrice: "118" },
  { category: "أمبولات ومحاليل", name: "فانكومايسين 1جم فانكوباكت vancomycin", unit: "فيال", purchasePrice: "78.75", nafqaPrice: "84.26", ahalyPrice: "204" },
  { category: "أمبولات ومحاليل", name: "كارديكسين / لانوكسين (ديجوكسين / Cardixin / Lanoxin / Digoxin)", unit: "امبول", purchasePrice: "5.88", nafqaPrice: "6.29", ahalyPrice: "10" },
  { category: "أمبولات ومحاليل", name: "كافيين سيترات / انكافاين (أنفاكافين / أسيتوفنت / Caffeine Citrate / Encafine)", unit: "امبول", purchasePrice: "23.10", nafqaPrice: "24.72", ahalyPrice: "30" },
  { category: "أمبولات ومحاليل", name: "كالسيوم كالسيونات calcium", unit: "امبول", purchasePrice: "17.33", nafqaPrice: "18.54", ahalyPrice: "23" },
  { category: "أمبولات ومحاليل", name: "كوليكسين colomysunny مصري", unit: "امبول", purchasePrice: "98.70", nafqaPrice: "105.61", ahalyPrice: "49" },
  { category: "أمبولات ومحاليل", name: "كوليكسين colixin مستورد", unit: "فيال", purchasePrice: "274.24", nafqaPrice: "293.44", ahalyPrice: "322" },
  { category: "أمبولات ومحاليل", name: "كابرون hemoxamine kapron", unit: "امبول", purchasePrice: "10.50", nafqaPrice: "11.24", ahalyPrice: "15" },
  { category: "أمبولات ومحاليل", name: "كليكسان 80 clexane", unit: "سرنجة", purchasePrice: "180.30", nafqaPrice: "192.92", ahalyPrice: "208.5" },
  { category: "أمبولات ومحاليل", name: "كليكسان 40 clexane", unit: "سرنجة", purchasePrice: "134.42", nafqaPrice: "143.83", ahalyPrice: "155.5" },
  { category: "أمبولات ومحاليل", name: "إينوكسابارين 40 (Enoxaparin 40)", unit: "سرنجة", purchasePrice: "101.02", nafqaPrice: "128.00", ahalyPrice: "-" },
  { category: "أمبولات ومحاليل", name: "كال هيبارين heparin", unit: "امبول", purchasePrice: "36.65", nafqaPrice: "39.21", ahalyPrice: "47.5" },
  { category: "أمبولات ومحاليل", name: "كيتورولاك 15 adolor كيتولاك ketorolac", unit: "امبول", purchasePrice: "3.99", nafqaPrice: "4.27", ahalyPrice: "10" },
  { category: "أمبولات ومحاليل", name: "كيتورولاك 30 كيتولاك ketorolac", unit: "امبول", purchasePrice: "4.20", nafqaPrice: "4.49", ahalyPrice: "12" },
  { category: "أمبولات ومحاليل", name: "كتالار / كيتالار (كيتامين / Ketalar / Ketamine)", unit: "فيال", purchasePrice: "31.50", nafqaPrice: "33.71", ahalyPrice: "51" },
  { category: "أمبولات ومحاليل", name: "سكسينيل كولين (سكيولين / Succinylcholine)", unit: "امبول", purchasePrice: "10.50", nafqaPrice: "11.24", ahalyPrice: "17.5" },
  { category: "أمبولات ومحاليل", name: "ليدوكايين 2% أمبول (زيلوكايين / Xylocaine / Lidocaine)", unit: "امبول", purchasePrice: "5.09", nafqaPrice: "5.45", ahalyPrice: "9" },
  { category: "أمبولات ومحاليل", name: "ليدوكايين 2% فيال (زيلوكايين / Xylocaine / Lidocaine)", unit: "فيال", purchasePrice: "21.78", nafqaPrice: "23.30", ahalyPrice: "33" },
  { category: "أمبولات ومحاليل", name: "ليفونور / ليفونورادريينالين 1مجم (Levonor / Norepinephrine)", unit: "امبول", purchasePrice: "32.55", nafqaPrice: "34.83", ahalyPrice: "76" },
  { category: "أمبولات ومحاليل", name: "ليفونور / ليفونورادريينالين 4مجم (Levonor / Norepinephrine)", unit: "امبول", purchasePrice: "16.80", nafqaPrice: "17.98", ahalyPrice: "48" },
  { category: "أمبولات ومحاليل", name: "ليفوفلوكساسين 750 (تافانيك / Levofloxacin / Tavanic)", unit: "فيال", purchasePrice: "30.45", nafqaPrice: "32.58", ahalyPrice: "102" },
  { category: "أمبولات ومحاليل", name: "تافانيك 500 / ليفوفلوكساسين 500 (Tavanic 500mg / Levofloxacin)", unit: "فيال", purchasePrice: "26.25", nafqaPrice: "28.10", ahalyPrice: "39.25" },
  { category: "أمبولات ومحاليل", name: "ليوسينتس (Lucentis / Ranibizumab)", unit: "سرنجة", purchasePrice: "3563.00", nafqaPrice: "3812.41", ahalyPrice: "4083.5" },
  { category: "أمبولات ومحاليل", name: "لولا ويست / هيباميرز (Lola West / Hepa-Merz)", unit: "امبول", purchasePrice: "21.53", nafqaPrice: "23.03", ahalyPrice: "37" },
  { category: "أمبولات ومحاليل", name: "لانتوس قلم (Lantus SoloStar Pen)", unit: "امبول", purchasePrice: "203.30", nafqaPrice: "217.53", ahalyPrice: "249" },
  { category: "أمبولات ومحاليل", name: "لابيتالول / لابيبرس (Labetalol / Labipress)", unit: "امبول", purchasePrice: "31.50", nafqaPrice: "33.71", ahalyPrice: "42.25" },
  { category: "أمبولات ومحاليل", name: "بروبرانولول / أندرال / مايستروتنس (Propranolol / Inderal / Maestrotens)", unit: "امبول", purchasePrice: "7.14", nafqaPrice: "7.64", ahalyPrice: "12" },
  { category: "أمبولات ومحاليل", name: "ماغنسيوم سولفات (Magnesium Sulfate)", unit: "امبول", purchasePrice: "10.94", nafqaPrice: "11.71", ahalyPrice: "12" },
  { category: "أمبولات ومحاليل", name: "ميثيرجين (Methergine / Methylergometrine)", unit: "امبول", purchasePrice: "6.83", nafqaPrice: "7.30", ahalyPrice: "10" },
  { category: "أمبولات ومحاليل", name: "ميكستارد 70/30 فيال مستورد (Mixtard 70/30)", unit: "فيال", purchasePrice: "105.00", nafqaPrice: "112.35", ahalyPrice: "130" },
  { category: "أمبولات ومحاليل", name: "ميكستارد 70/30 بنفل / بنسل مصري (Mixtard Penfill)", unit: "امبول", purchasePrice: "50.40", nafqaPrice: "53.93", ahalyPrice: "56" },
  { category: "أمبولات ومحاليل", name: "ميباكين أحمر (Mepachyne Red)", unit: "امبول", purchasePrice: "11.13", nafqaPrice: "11.91", ahalyPrice: "13" },
  { category: "أمبولات ومحاليل", name: "ميباكين أزرق (Mepachyne Blue)", unit: "امبول", purchasePrice: "12.53", nafqaPrice: "13.40", ahalyPrice: "15" },
  { category: "أمبولات ومحاليل", name: "ماركين لايت", unit: "امبول", purchasePrice: "16.28", nafqaPrice: "17.41", ahalyPrice: "47.5" },
  { category: "أمبولات ومحاليل", name: "ميتوكلوبراميد بريمبران metoclopramide primperan", unit: "امبول", purchasePrice: "4.52", nafqaPrice: "4.83", ahalyPrice: "8" },
  { category: "أمبولات ومحاليل", name: "ميثوتريكسات unitrexate methotrexate", unit: "امبول", purchasePrice: "59.85", nafqaPrice: "64.04", ahalyPrice: "77" },
  { category: "أمبولات ومحاليل", name: "ميروبينيم 1جم ميرونام meropenem meronem", unit: "امبول", purchasePrice: "136.50", nafqaPrice: "146.06", ahalyPrice: "295" },
  { category: "أمبولات ومحاليل", name: "ميروبينيم 500مجم ميرونام meropenem meronem", unit: "امبول", purchasePrice: "89.25", nafqaPrice: "95.50", ahalyPrice: "216" },
  { category: "أمبولات ومحاليل", name: "ميترونيدازول 500 فلاجيل metronidazole flagyl", unit: "امبول", purchasePrice: "22.05", nafqaPrice: "23.59", ahalyPrice: "31" },
  { category: "أمبولات ومحاليل", name: "ميداثيتك (ميدازولام / دورميكام / آمون / Midathetic / Midazolam / Dormicum)", unit: "امبول", purchasePrice: "6.56", nafqaPrice: "7.02", ahalyPrice: "14" },
  { category: "أمبولات ومحاليل", name: "مصل كبدى ب", unit: "فيال", purchasePrice: "0.00", nafqaPrice: "0.00", ahalyPrice: "0" },
  { category: "أمبولات ومحاليل", name: "نيوستجمين (Neostigmine)", unit: "امبول", purchasePrice: "2.89", nafqaPrice: "3.09", ahalyPrice: "10" },
  { category: "أمبولات ومحاليل", name: "نيوستجمين (Neostigmine)", unit: "فيال", purchasePrice: "14.91", nafqaPrice: "15.95", ahalyPrice: "18" },
  { category: "أمبولات ومحاليل", name: "يونيكتام 1.5جم فيال (سلبوكتام + أمبيسيلين / Unictam 1.5g / Ampicillin + Sulbactam / Sulbin)", unit: "فيال", purchasePrice: "36.75", nafqaPrice: "39.32", ahalyPrice: "75" },
  { category: "أمبولات ومحاليل", name: "يونيكتام 0.75جم / 750مجم فيال (سلبوكتام + أمبيسيلين / Unictam 0.75g / Ampicillin + Sulbactam)", unit: "فيال", purchasePrice: "22.05", nafqaPrice: "23.59", ahalyPrice: "45" },
  { category: "أمبولات ومحاليل", name: "يونيكتام 375مجم فيال (سلبوكتام + أمبيسيلين / Unictam 375mg / Ampicillin + Sulbactam)", unit: "فيال", purchasePrice: "15.75", nafqaPrice: "16.85", ahalyPrice: "30" },
  { category: "أمبولات ومحاليل", name: "هيبارين 5000 وحدة heparin", unit: "امبول", purchasePrice: "40.95", nafqaPrice: "43.82", ahalyPrice: "54" },
  { category: "أمبولات ومحاليل", name: "هيدروكورتيزون سولوكورتيف hydrocortisone", unit: "امبول", purchasePrice: "19.95", nafqaPrice: "21.35", ahalyPrice: "26" },
  { category: "أمبولات ومحاليل", name: "هالوبيريدول haloperidol", unit: "امبول", purchasePrice: "9.66", nafqaPrice: "10.34", ahalyPrice: "-" },
  { category: "أمبولات ومحاليل", name: "هيفي ماركين", unit: "امبول", purchasePrice: "15.75", nafqaPrice: "16.85", ahalyPrice: "37" },
  { category: "أمبولات ومحاليل", name: "بوبيفاكين 750 ماركين", unit: "فيال", purchasePrice: "13.97", nafqaPrice: "14.94", ahalyPrice: "39" },
  { category: "أمبولات ومحاليل", name: "بوبيفاكين 1500 ماركين", unit: "فيال", purchasePrice: "23.10", nafqaPrice: "24.72", ahalyPrice: "56" },
  { category: "أمبولات ومحاليل", name: "مورفين 20 morphine", unit: "امبول", purchasePrice: "14", nafqaPrice: "14.98", ahalyPrice: "17.5" },
  { category: "أمبولات ومحاليل", name: "نالوفين 20مجم / نالبوفين (Nalufin / Nalbuphine 20mg)", unit: "امبول", purchasePrice: "21", nafqaPrice: "22.47", ahalyPrice: "45" },
  { category: "أمبولات ومحاليل", name: "بيثيدين 100 pethidine", unit: "امبول", purchasePrice: "13.86", nafqaPrice: "14.83", ahalyPrice: "15" },
  { category: "أمبولات ومحاليل", name: "بيثيدين 50 pethidine", unit: "امبول", purchasePrice: "9.45", nafqaPrice: "10.11", ahalyPrice: "13" },
  { category: "أمبولات ومحاليل", name: "فنتانيل fentanyl", unit: "امبول", purchasePrice: "17.85", nafqaPrice: "19.10", ahalyPrice: "19.1" },
  { category: "أمبولات ومحاليل", name: "هيوسين بيوتيل بروميد hyoscine", unit: "امبول", purchasePrice: "6.00", nafqaPrice: "6.42", ahalyPrice: "7" },
  { category: "أمبولات ومحاليل", name: "جرانسيترون 1مجم / جرانترون (كايتريل / Granisetron / Kytril / Granitron)", unit: "امبول", purchasePrice: "14.75", nafqaPrice: "15.97", ahalyPrice: "30" },
  { category: "أمبولات ومحاليل", name: "باراسيتامول 1جم inod امبول", unit: "امبول", purchasePrice: "14.18", nafqaPrice: "15.20", ahalyPrice: "20" },
  { category: "أمبولات ومحاليل", name: "سموفكابفين", unit: "زجاجة", purchasePrice: "690.90", nafqaPrice: "739.3", ahalyPrice: "830" },
  { category: "أمبولات ومحاليل", name: "داى بيتيفين", unit: "زجاجة", purchasePrice: "434.70", nafqaPrice: "465.1", ahalyPrice: "520" },
  { category: "أمبولات ومحاليل", name: "اميبارين 250 مل", unit: "زجاجة", purchasePrice: "162.75", nafqaPrice: "174.1", ahalyPrice: "220" },
  { category: "أمبولات ومحاليل", name: "بان امين جي", unit: "زجاجة", purchasePrice: "90.62", nafqaPrice: "97.0", ahalyPrice: "162" },
  { category: "أمبولات ومحاليل", name: "جلوكوز 5% glucose", unit: "زجاجة", purchasePrice: "23.54", nafqaPrice: "25.2", ahalyPrice: "30" },
  { category: "أمبولات ومحاليل", name: "جلوكوز 10% glucose", unit: "زجاجة", purchasePrice: "24.15", nafqaPrice: "25.8", ahalyPrice: "30" },
  { category: "أمبولات ومحاليل", name: "جلوكوز 25% glucose", unit: "زجاجة", purchasePrice: "28.35", nafqaPrice: "30.3", ahalyPrice: "35" },
  { category: "أمبولات ومحاليل", name: "جلوكوز ملحى", unit: "زجاجة", purchasePrice: "19.95", nafqaPrice: "21.3", ahalyPrice: "25" },
  { category: "أمبولات ومحاليل", name: "ملح 0.9% 500مل saline", unit: "زجاجة", purchasePrice: "20.31", nafqaPrice: "21.7", ahalyPrice: "25" },
  { category: "أمبولات ومحاليل", name: "رينجر ringer", unit: "زجاجة", purchasePrice: "20.48", nafqaPrice: "21.9", ahalyPrice: "25" },
  { category: "أمبولات ومحاليل", name: "رينجر لاكتات ringer lactate", unit: "زجاجة", purchasePrice: "19.43", nafqaPrice: "20.8", ahalyPrice: "25" },
  { category: "أمبولات ومحاليل", name: "ملح غسيل التر", unit: "زجاجة", purchasePrice: "25.00", nafqaPrice: "26.8", ahalyPrice: "30" },
  { category: "أمبولات ومحاليل", name: "ملح 0.9% 250مل saline", unit: "زجاجة", purchasePrice: "15.75", nafqaPrice: "16.9", ahalyPrice: "20" },
  { category: "أمبولات ومحاليل", name: "ماء مقطر sterile water", unit: "زجاجة", purchasePrice: "24.99", nafqaPrice: "26.7", ahalyPrice: "30" },
  { category: "أمبولات ومحاليل", name: "نيومنت", unit: "زجاجة", purchasePrice: "22.05", nafqaPrice: "23.6", ahalyPrice: "27" },
  { category: "أمبولات ومحاليل", name: "هيماجل فولفين", unit: "زجاجة", purchasePrice: "157.50", nafqaPrice: "168.5", ahalyPrice: "180" },
  { category: "أمبولات ومحاليل", name: "كبسين", unit: "زجاجة", purchasePrice: "199.50", nafqaPrice: "213.5", ahalyPrice: "230" },
  { category: "أمبولات ومحاليل", name: "ملح 0.45% 500مل saline", unit: "زجاجة", purchasePrice: "20.31", nafqaPrice: "21.7", ahalyPrice: "25" },
  { category: "أمبولات ومحاليل", name: "ملح 3% saline", unit: "زجاجة", purchasePrice: "21.48", nafqaPrice: "23.0", ahalyPrice: "27" },
  { category: "أمبولات ومحاليل", name: "رنجر اسيتات ringer acetate", unit: "زجاجة", purchasePrice: "21.09", nafqaPrice: "22.6", ahalyPrice: "27" },
  { category: "أمبولات ومحاليل", name: "اميبارين 500 مل", unit: "زجاجة", purchasePrice: "220.50", nafqaPrice: "235.9", ahalyPrice: "250" },
  { category: "أمبولات ومحاليل", name: "امينوليبان", unit: "زجاجة", purchasePrice: "142.96", nafqaPrice: "153.0", ahalyPrice: "183" },
  { category: "أمبولات ومحاليل", name: "كيدمين 200مل محلول أحماض أمينية لمرضى الكلى / الفشل الكلوي (Kidmin Infusion / Amino acids for Renal Failure)", unit: "زجاجة", purchasePrice: "199.50", nafqaPrice: "213.50", ahalyPrice: "230" },
  { category: "أمبولات ومحاليل", name: "مانيتول mannitol", unit: "زجاجة", purchasePrice: "43.74", nafqaPrice: "46.8", ahalyPrice: "58" },

  // Section 2: متنوعات
  { category: "متنوعات", name: "اسي زادكس aescin هيموكلار - ريباريل", unit: "انبوبه", purchasePrice: "25.36", nafqaPrice: "27.1", ahalyPrice: "30" },
  { category: "متنوعات", name: "استيل سيستايين acetyl cysteine200", unit: "كيس", purchasePrice: "2.52", nafqaPrice: "2.7", ahalyPrice: "505" },
  { category: "متنوعات", name: "استيل سيستايين acetyl cysteine600", unit: "كيس", purchasePrice: "2.99", nafqaPrice: "3.2", ahalyPrice: "7" },
  { category: "متنوعات", name: "ايسوميبرازول 10 نكسيوم كيس nexium", unit: "كيس", purchasePrice: "5.20", nafqaPrice: "5.6", ahalyPrice: "9" },
  { category: "متنوعات", name: "انماكس حقنه", unit: "زجاجه", purchasePrice: "28.35", nafqaPrice: "30.3", ahalyPrice: "40" },
  { category: "متنوعات", name: "بيتادين 7.5% povidone iodine betadine", unit: "زجاجه التر", purchasePrice: "322.35", nafqaPrice: "344.9", ahalyPrice: "475" },
  { category: "متنوعات", name: "بيتادين 10% povidone iodine betadine", unit: "زجاجه التر", purchasePrice: "276.32", nafqaPrice: "295.7", ahalyPrice: "400" },
  { category: "متنوعات", name: "بيتادين 10% 120مل مطهر (Betadine 10% Antiseptic Solution 120ml / Povidone Iodine)", unit: "زجاجه", purchasePrice: "59.87", nafqaPrice: "64.10", ahalyPrice: "80" },
  { category: "متنوعات", name: "بنتابرن 15 جم ميبو mebo", unit: "انبوبه", purchasePrice: "16.91", nafqaPrice: "18.1", ahalyPrice: "64" },
  { category: "متنوعات", name: "بنتابرن 30 جم ميبو mebo", unit: "انبوبه", purchasePrice: "31.40", nafqaPrice: "33.6", ahalyPrice: "80" },
  { category: "متنوعات", name: "بوتاسيوم كلورايد potassium chloride", unit: "زجاجه", purchasePrice: "7.37", nafqaPrice: "7.9", ahalyPrice: "29" },
  { category: "متنوعات", name: "بيفتراسين / بيفاتراسين / بيقتراسين bacitracin + neomycin bivatracin bivracin بخاخ", unit: "بخاخه", purchasePrice: "45.89", nafqaPrice: "49.1", ahalyPrice: "83" },
  { category: "متنوعات", name: "بينوكس benoxinate 0.4% benox", unit: "زجاجه", purchasePrice: "11.03", nafqaPrice: "11.8", ahalyPrice: "23" },
  { category: "متنوعات", name: "بارامول شراب سيتال paramol cetal", unit: "زجاجه", purchasePrice: "14.70", nafqaPrice: "15.7", ahalyPrice: "31" },
  { category: "متنوعات", name: "بارامول اقماع paramol cetal", unit: "قمع", purchasePrice: "1.10", nafqaPrice: "1.2", ahalyPrice: "3" },
  { category: "متنوعات", name: "توسين شراب / توسين ميكس للكحة (Tussin Syrup / Tussin Mix)", unit: "زجاجه", purchasePrice: "16.66", nafqaPrice: "17.80", ahalyPrice: "35" },
  { category: "متنوعات", name: "توبيراميسين afazir توبراديكس قطره tobramycin", unit: "زجاجه", purchasePrice: "5.25", nafqaPrice: "5.6", ahalyPrice: "20" },
  { category: "متنوعات", name: "توبيرين مرهم عين tobrin", unit: "انبوبه", purchasePrice: "8.40", nafqaPrice: "9.0", ahalyPrice: "23" },
  { category: "متنوعات", name: "جلسرين لبوس كبار glycerin", unit: "قمع", purchasePrice: "1.41", nafqaPrice: "1.5", ahalyPrice: "2.2" },
  { category: "متنوعات", name: "جنتا ميسين كريم Gentamicin", unit: "انبوبه", purchasePrice: "11.27", nafqaPrice: "12.1", ahalyPrice: "22" },
  { category: "متنوعات", name: "جاست ريج trimebutine 24mg/5ml gast reg", unit: "زجاجه", purchasePrice: "24.15", nafqaPrice: "25.8", ahalyPrice: "33" },
  { category: "متنوعات", name: "ديكلوفين 1% رومافين diclofenac romafen", unit: "انبوبه", purchasePrice: "6.70", nafqaPrice: "7.2", ahalyPrice: "18" },
  { category: "متنوعات", name: "زنك اوليف (وادي بيبي) zinc olive", unit: "انبوبه", purchasePrice: "11.52", nafqaPrice: "12.3", ahalyPrice: "34" },
  { category: "متنوعات", name: "زيلوكايين سبراي lidocaine 10% xylocaine", unit: "زجاجه", purchasePrice: "25.73", nafqaPrice: "27.5", ahalyPrice: "38" },
  { category: "متنوعات", name: "سيلفر سلفاديازين silver sulfadiazine 1% ديرمازين dermazin", unit: "انبوبه", purchasePrice: "12.34", nafqaPrice: "13.2", ahalyPrice: "28" },
  { category: "متنوعات", name: "سالبيوتامول salbutamol 0.5 respirator فاركولين farcolin", unit: "زجاجه", purchasePrice: "14.70", nafqaPrice: "15.7", ahalyPrice: "37" },
  { category: "متنوعات", name: "فنتال بخاخة / فياسالمول بلاس (Vental Inhaler / Viasalmol Plus / Salbutamol)", unit: "بخاخه", purchasePrice: "57.49", nafqaPrice: "61.50", ahalyPrice: "72" },
  { category: "متنوعات", name: "سيدكس مطهر أدوات ومناظير (Cidex Disinfectant Solution 2% / Glutaraldehyde)", unit: "زجاجه", purchasePrice: "377.63", nafqaPrice: "404.10", ahalyPrice: "-" },
  { category: "متنوعات", name: "فيوسيدين fucidin acid كريم", unit: "انبوبه", purchasePrice: "27.93", nafqaPrice: "29.9", ahalyPrice: "44" },
  { category: "متنوعات", name: "لاكتيلوز (دوفلاك) lactulose duphalac", unit: "زجاجه", purchasePrice: "70.35", nafqaPrice: "75.3", ahalyPrice: "143" },
  { category: "متنوعات", name: "ميدرابيد 0.5% tropicamide قطره", unit: "زجاجه", purchasePrice: "14.18", nafqaPrice: "15.20", ahalyPrice: "27" },
  { category: "متنوعات", name: "ميدرابيد 1% tropicamide قطره", unit: "زجاجه", purchasePrice: "17.33", nafqaPrice: "18.50", ahalyPrice: "32" },
  { category: "متنوعات", name: "سيكلوبنتولات 1% / سيكلوجل / سويكسولات قطرة عين (Cyclopentolate 1% / Cyclogyl / Suixlate Eye Drops)", unit: "زجاجه", purchasePrice: "11.29", nafqaPrice: "12.10", ahalyPrice: "15" },
  { category: "متنوعات", name: "ماء اكسجين hydrogen peroxide 20%", unit: "زجاجه", purchasePrice: "8.47", nafqaPrice: "9.1", ahalyPrice: "15" },
  { category: "متنوعات", name: "ماء اكسجين hydrogen peroxide 10%", unit: "زجاجه", purchasePrice: "7.37", nafqaPrice: "7.9", ahalyPrice: "15" },
  { category: "متنوعات", name: "بري نان / برينان لبن أطفال (Pre NAN / PreNAN Infant Milk / Formula for Premature Infants)", unit: "علبة", purchasePrice: "231.00", nafqaPrice: "247.20", ahalyPrice: "380" },
  { category: "متنوعات", name: "نيستاتين nystatin", unit: "زجاجه", purchasePrice: "14.18", nafqaPrice: "15.2", ahalyPrice: "22" },
  { category: "متنوعات", name: "في دروب / ديفيتون دي (Vidrop / Diviton D / Vitamin D3 Drops)", unit: "زجاجه", purchasePrice: "15.66", nafqaPrice: "16.80", ahalyPrice: "40" },
  { category: "متنوعات", name: "فنتوكف شراب (Ventocough Syrup)", unit: "زجاجه", purchasePrice: "33.14", nafqaPrice: "15.30", ahalyPrice: "25" },
  { category: "متنوعات", name: "كيناكومب / ابيكومب (Kenacomb / Apicomb Cream & Ointment)", unit: "انبوبه", purchasePrice: "10.45", nafqaPrice: "11.20", ahalyPrice: "22" },
  { category: "متنوعات", name: "نيترودرم 5 مجم لصقات / لاصقة (Nitroderm TTS 5mg Patch / Nitroglycerin)", unit: "لاصقة", purchasePrice: "11.16", nafqaPrice: "11.90", ahalyPrice: "15" },
  { category: "متنوعات", name: "يورإيد (UR-AID)", unit: "كيس", purchasePrice: "2.00", nafqaPrice: "2.10", ahalyPrice: "3.2" },
  { category: "متنوعات", name: "نيوميون (Neomune / Ne-Mune)", unit: "زجاجة", purchasePrice: "850.50", nafqaPrice: "910", ahalyPrice: "1054.5" },
  { category: "متنوعات", name: "انشور (Ensure)", unit: "زجاجة", purchasePrice: "313.16", nafqaPrice: "335.1", ahalyPrice: "500" },
  { category: "متنوعات", name: "ببتامين (Peptamen)", unit: "زجاجة", purchasePrice: "849.45", nafqaPrice: "908.9", ahalyPrice: "1200" },
  { category: "متنوعات", name: "دوميجست شراب (Domigest Syrup / Domegest / Digest)", unit: "زجاجة", purchasePrice: "8.66", nafqaPrice: "9.3", ahalyPrice: "12.5" },
  { category: "متنوعات", name: "هيدروفرين إنريتش حديد قطرة (Hydroferrin Enrich Iron Drops)", unit: "زجاجة", purchasePrice: "19.59", nafqaPrice: "21.0", ahalyPrice: "26" },

  // Section 3: أقراص
  { category: "أقراص", name: "اتينو 50 مجم ateno", unit: "قرص", purchasePrice: "0.45", nafqaPrice: "0.48", ahalyPrice: "1" },
  { category: "أقراص", name: "اتوريزا 10/40 atoriza", unit: "قرص", purchasePrice: "3.36", nafqaPrice: "3.60", ahalyPrice: "7.5" },
  { category: "أقراص", name: "تجريتول / ارباتج (Tegretol / Arbatag / Carbamazepine 200mg)", unit: "قرص", purchasePrice: "1.47", nafqaPrice: "1.57", ahalyPrice: "2.5" },
  { category: "أقراص", name: "تجريتول / ارباتج سي ار (Tegretol CR / Arbatag CR / Carbamazepine CR 200mg)", unit: "قرص", purchasePrice: "1.51", nafqaPrice: "1.62", ahalyPrice: "2.7" },
  { category: "أقراص", name: "ارث فرى leflunamide arthfree", unit: "قرص", purchasePrice: "4.83", nafqaPrice: "5.17", ahalyPrice: "8.7" },
  { category: "أقراص", name: "ازيثرومايسين 500 زيثروماكس azithromycin zithromax", unit: "قرص", purchasePrice: "6.04", nafqaPrice: "6.46", ahalyPrice: "14.5" },
  { category: "أقراص", name: "استيل سالسليك اسيد 81/75 اسبرين acetylsalicylic acid aspirin", unit: "قرص", purchasePrice: "0.32", nafqaPrice: "0.34", ahalyPrice: "0.55" },
  { category: "أقراص", name: "استيل سالسليك اسيد 81 اسبريكارلو acetylsalicylic acid aspicardo", unit: "قرص", purchasePrice: "0.50", nafqaPrice: "0.54", ahalyPrice: "1.55" },
  { category: "أقراص", name: "استيل سالسليك اسيد 100 اسبرين 100 acetylsalicylic acid aspirin", unit: "قرص", purchasePrice: "0.74", nafqaPrice: "0.79", ahalyPrice: "1.8" },
  { category: "أقراص", name: "التروكسين 50 مجم euthyrox roxine 50 mg", unit: "قرص", purchasePrice: "0.78", nafqaPrice: "0.83", ahalyPrice: "0.92" },
  { category: "أقراص", name: "الداكتون 25 مجم aldactone", unit: "قرص", purchasePrice: "1.03", nafqaPrice: "1.10", ahalyPrice: "1.8" },
  { category: "أقراص", name: "ابيكسيبان 2.5 مجم apixaban 2.5mg", unit: "قرص", purchasePrice: "2.42", nafqaPrice: "2.58", ahalyPrice: "8.3" },
  { category: "أقراص", name: "ابيكسيبان 5 مجم apixaban 5mg", unit: "قرص", purchasePrice: "2.76", nafqaPrice: "2.95", ahalyPrice: "10.55" },
  { category: "أقراص", name: "امبيزيم chymotrypsin+trypsin ambezim", unit: "قرص", purchasePrice: "1.33", nafqaPrice: "1.43", ahalyPrice: "1.5" },
  { category: "أقراص", name: "انداباميد 2.5 indapamide", unit: "قرص", purchasePrice: "0.44", nafqaPrice: "0.47", ahalyPrice: "0.57" },
  { category: "أقراص", name: "اموسريبرال بلس (Amocerebral Plus / Cinnarizine + Dimenhydrinate)", unit: "قرص", purchasePrice: "0.88", nafqaPrice: "0.94", ahalyPrice: "1.2" },
  { category: "أقراص", name: "انترستو sacubitril/vasartan 50 mg entresto", unit: "قرص", purchasePrice: "29.40", nafqaPrice: "31.46", ahalyPrice: "60.7" },
  { category: "أقراص", name: "اوسيلتاميفير تاميفلو oseltamivir tamiflu", unit: "قرص", purchasePrice: "18.48", nafqaPrice: "19.77", ahalyPrice: "20" },
  { category: "أقراص", name: "اوكسي بيوتينين oxybutynin يوريبان", unit: "قرص", purchasePrice: "1.53", nafqaPrice: "1.64", ahalyPrice: "1.8" },
  { category: "أقراص", name: "اوميز 40 omeprazole omez", unit: "قرص", purchasePrice: "1.31", nafqaPrice: "1.40", ahalyPrice: "6.5" },
  { category: "أقراص", name: "اميودارون cardiomep 200 كوردارون cordarone", unit: "قرص", purchasePrice: "2.31", nafqaPrice: "2.47", ahalyPrice: "3.2" },
  { category: "أقراص", name: "املوديبين 10 مجم الكابرس amlodipine alcapress", unit: "قرص", purchasePrice: "0.68", nafqaPrice: "0.73", ahalyPrice: "1.1" },
  { category: "أقراص", name: "ايراستبكس 20 مجم erastapex", unit: "قرص", purchasePrice: "1.30", nafqaPrice: "1.39", ahalyPrice: "2.5" },
  { category: "أقراص", name: "ايراستبكس 20+5 sartan20+amlodipine5mg erastapex", unit: "قرص", purchasePrice: "1.68", nafqaPrice: "1.80", ahalyPrice: "2.9" },
  { category: "أقراص", name: "ايراستبكس تريو 20/5/12.5 erastapex trio", unit: "قرص", purchasePrice: "1.68", nafqaPrice: "1.80", ahalyPrice: "3" },
  { category: "أقراص", name: "ايراستبكس تريو 40/10/25 erastapex trio", unit: "قرص", purchasePrice: "2.36", nafqaPrice: "2.53", ahalyPrice: "4.2" },
  { category: "أقراص", name: "اتورفاستاتين 40 مجم اتور atorvastatin ator", unit: "قرص", purchasePrice: "1.19", nafqaPrice: "1.27", ahalyPrice: "4" },
  { category: "أقراص", name: "الفاكالسيدول 25 وان الفا - بونكير alfacalcidol one alpha bonecare", unit: "قرص", purchasePrice: "1.84", nafqaPrice: "1.97", ahalyPrice: "2.4" },
  { category: "أقراص", name: "اورسكول / اورسوفالك ursodeoxycholic acid ursochol ursofalk", unit: "قرص", purchasePrice: "4.33", nafqaPrice: "4.63", ahalyPrice: "6.1" },
  { category: "أقراص", name: "ازاثيوبرين 50 azathioprine", unit: "قرص", purchasePrice: "1.47", nafqaPrice: "1.57", ahalyPrice: "2.5" },
  { category: "أقراص", name: "اميوران 50 imuran by name", unit: "قرص", purchasePrice: "4.59", nafqaPrice: "4.91", ahalyPrice: "5.08" },
  { category: "أقراص", name: "اوجمنتين 1جم augmentin 1g", unit: "قرص", purchasePrice: "4.94", nafqaPrice: "5.28", ahalyPrice: "9.6" },
  { category: "أقراص", name: "ايفابرادين بروكولان ivabradine procoralan", unit: "قرص", purchasePrice: "2.63", nafqaPrice: "2.81", ahalyPrice: "5.8" },
  { category: "أقراص", name: "ايمباجليفلوزين 25 empagliflozin", unit: "قرص", purchasePrice: "2.63", nafqaPrice: "2.81", ahalyPrice: "6" },
  { category: "أقراص", name: "بيرافين pirafene", unit: "قرص", purchasePrice: "0.17", nafqaPrice: "0.18", ahalyPrice: "0.5" },
  { category: "أقراص", name: "بيسوبرولول فيوماريت 5 bisoprolol", unit: "قرص", purchasePrice: "0.53", nafqaPrice: "0.56", ahalyPrice: "2.1" },
  { category: "أقراص", name: "بيسوبرولول فيوماريت 5 كونكور bisoprolol concor by name", unit: "قرص", purchasePrice: "1.91", nafqaPrice: "2.04", ahalyPrice: "2.4" },
  { category: "أقراص", name: "بيسولوك d bisolock d", unit: "قرص", purchasePrice: "0.74", nafqaPrice: "0.79", ahalyPrice: "2.1" },
  { category: "أقراص", name: "بانتوبرازول 40 بروتوفكس pantoprazole protofix", unit: "قرص", purchasePrice: "1.42", nafqaPrice: "1.52", ahalyPrice: "6.8" },
  { category: "أقراص", name: "بانتوبرازول 20 pantoprazole", unit: "قرص", purchasePrice: "1.00", nafqaPrice: "1.07", ahalyPrice: "4.7" },
  { category: "أقراص", name: "بريدنيزيلون 5 ايبكوبيريد prednisolone epicoprid", unit: "قرص", purchasePrice: "1.42", nafqaPrice: "1.52", ahalyPrice: "2.3" },
  { category: "أقراص", name: "بريدنيزيلون 5 اركو prednisolone", unit: "قرص", purchasePrice: "0.61", nafqaPrice: "0.65", ahalyPrice: "1.2" },
  { category: "أقراص", name: "بريدنيزيلون 20 ايبكوبيريد 20 prednisolone epicoprid", unit: "قرص", purchasePrice: "3.89", nafqaPrice: "4.16", ahalyPrice: "5.2" },
  { category: "أقراص", name: "بروبرانولول 10مجم (اندرال / مايستروتنس / Propranolol / Inderal / Maestrotens)", unit: "قرص", purchasePrice: "0.26", nafqaPrice: "0.28", ahalyPrice: "0.35" },
  { category: "أقراص", name: "باراسيتامول 500 paracetamol", unit: "قرص", purchasePrice: "0.37", nafqaPrice: "0.39", ahalyPrice: "1.2" },
  { category: "أقراص", name: "باراسيتامول 1جم دوليبران paracetamol doliprane", unit: "قرص", purchasePrice: "1.44", nafqaPrice: "1.54", ahalyPrice: "1.9" },
  { category: "أقراص", name: "بيروكسيكام 20 ديسبركام piroxicam dispercam", unit: "قرص", purchasePrice: "0.84", nafqaPrice: "0.90", ahalyPrice: "1.5" },
  { category: "أقراص", name: "بيراسيتام 400 مجم (نوتروبيل / Piracetam)", unit: "قرص", purchasePrice: "0.89", nafqaPrice: "0.95", ahalyPrice: "1.6" },
  { category: "أقراص", name: "بيليكول / رواكول (Bilichol / Rowachol / Bilcol)", unit: "قرص", purchasePrice: "1.00", nafqaPrice: "1.07", ahalyPrice: "1.35" },
  { category: "أقراص", name: "برليك ticagrelor 90mg brilique", unit: "قرص", purchasePrice: "5.57", nafqaPrice: "5.95", ahalyPrice: "13.7" },
  { category: "أقراص", name: "تامسولين tamsulosin tamsulin", unit: "قرص", purchasePrice: "1.47", nafqaPrice: "1.57", ahalyPrice: "4.45" },
  { category: "أقراص", name: "تروسيميد 5 اكساميد 5 مجم torasemide examide", unit: "قرص", purchasePrice: "0.84", nafqaPrice: "0.90", ahalyPrice: "2" },
  { category: "أقراص", name: "تروسيميد 10 اكساميد 10 مجم torasemide examide", unit: "قرص", purchasePrice: "0.87", nafqaPrice: "0.93", ahalyPrice: "3.1" },
  { category: "أقراص", name: "ترايكور ramipril 5mg + felodipine 5mg triacor", unit: "قرص", purchasePrice: "4.45", nafqaPrice: "4.76", ahalyPrice: "5.7" },
  { category: "أقراص", name: "تيراليبسى 500 مجم تيراليبسي tieralipsy", unit: "قرص", purchasePrice: "5.08", nafqaPrice: "5.44", ahalyPrice: "6.45" },
  { category: "أقراص", name: "تيراليبسى 500 مجم seizurless", unit: "قرص", purchasePrice: "2.47", nafqaPrice: "2.64", ahalyPrice: "6" },
  { category: "أقراص", name: "تيراليبسى 1جم tieralipsy", unit: "قرص", purchasePrice: "3.07", nafqaPrice: "3.28", ahalyPrice: "8.7" },
  { category: "أقراص", name: "ثيوتاسيد 600 thiotacid", unit: "قرص", purchasePrice: "3.89", nafqaPrice: "4.16", ahalyPrice: "6.5" },
  { category: "أقراص", name: "ثيوتاسيد 600 مركب ابن سينا - اخناتون thiotacid compound", unit: "قرص", purchasePrice: "5.60", nafqaPrice: "5.99", ahalyPrice: "7.5" },
  { category: "أقراص", name: "جلوبينكلاميد 5 ميتفورمين 500 جلوكان glibenclamide 5,metformin 500 glucan", unit: "قرص", purchasePrice: "0.89", nafqaPrice: "0.95", ahalyPrice: "1.6" },
  { category: "أقراص", name: "جليميبرايد 3مجم اماريل 3 مجم glimepiride amaryl", unit: "قرص", purchasePrice: "0.43", nafqaPrice: "0.46", ahalyPrice: "1.35" },
  { category: "أقراص", name: "جليميبرايد 4مجم glimepiride amaryl", unit: "قرص", purchasePrice: "0.58", nafqaPrice: "0.62", ahalyPrice: "0.8" },
  { category: "أقراص", name: "جابابنتين 400 مجم gabapentin", unit: "قرص", purchasePrice: "1.73", nafqaPrice: "1.85", ahalyPrice: "5.2" },
  { category: "أقراص", name: "جابابنتين 300 مجم جابتين gabapentin gaptin", unit: "قرص", purchasePrice: "3.30", nafqaPrice: "3.53", ahalyPrice: "4.2" },
  { category: "أقراص", name: "جاست ريج trimebutine 200 mg gast reg", unit: "قرص", purchasePrice: "1.89", nafqaPrice: "2.02", ahalyPrice: "2.8" },
  { category: "أقراص", name: "ديجليفلوز 5مجم فورسيجا 5 مجم dapagliflozin forxiga", unit: "قرص", purchasePrice: "1.47", nafqaPrice: "1.57", ahalyPrice: "6.1" },
  { category: "أقراص", name: "ديجليفلوز 10مجم فورسيجا 10 مجم dapagliflozin forxiga", unit: "قرص", purchasePrice: "2.05", nafqaPrice: "2.19", ahalyPrice: "10.2" },
  { category: "أقراص", name: "ديوزمين 500 مجم دافلون diosmin 500mg daflon", unit: "قرص", purchasePrice: "2.97", nafqaPrice: "3.18", ahalyPrice: "4.9" },
  { category: "أقراص", name: "ديباكين 500 مجم (صوديوم فالبروات / Depakine 500mg / Sodium Valproate)", unit: "قرص", purchasePrice: "3.85", nafqaPrice: "4.12", ahalyPrice: "4.8" },
  { category: "أقراص", name: "ديابيتونورم diabetonorm", unit: "قرص", purchasePrice: "1.79", nafqaPrice: "1.91", ahalyPrice: "3.33" },
  { category: "أقراص", name: "داونيسترولين daunisterolin", unit: "قرص", purchasePrice: "1.58", nafqaPrice: "1.69", ahalyPrice: "4.36" },
  { category: "أقراص", name: "داينيترا 5 مجم dinitra", unit: "قرص", purchasePrice: "0.16", nafqaPrice: "0.17", ahalyPrice: "0.53" },
  { category: "أقراص", name: "دياميكرون 60 مجم / دياميدازين (Diamicron / Diamedizen / Gliclazide)", unit: "قرص", purchasePrice: "1.42", nafqaPrice: "1.52", ahalyPrice: "2.4" },
  { category: "أقراص", name: "ديكلاك 150 diclac", unit: "قرص", purchasePrice: "3.15", nafqaPrice: "3.37", ahalyPrice: "6.6" },
  { category: "أقراص", name: "ديكلوفيناك بوتاسيوم 50 كتافلام diclofenac potassium cataflam", unit: "قرص", purchasePrice: "0.50", nafqaPrice: "0.54", ahalyPrice: "1.8" },
  { category: "أقراص", name: "ريفاروكسيبان rivaroxaban 10mg زاريلتو xarelto", unit: "قرص", purchasePrice: "1.74", nafqaPrice: "1.87", ahalyPrice: "7.6" },
  { category: "أقراص", name: "رانديل 10 مجم ادانكور نيكورانديل randil 10mg adancor nicorandil", unit: "قرص", purchasePrice: "1.16", nafqaPrice: "1.24", ahalyPrice: "2.2" },
  { category: "أقراص", name: "رامبيريل 1.25 مجم تريتاس ramipril 1.25mg tritace", unit: "قرص", purchasePrice: "2.03", nafqaPrice: "2.17", ahalyPrice: "3.15" },
  { category: "أقراص", name: "رامبيريل 5 مجم تريتاس ramipril 5mg tritace", unit: "قرص", purchasePrice: "3.69", nafqaPrice: "3.94", ahalyPrice: "5.43" },
  { category: "أقراص", name: "سلفاسلازين 500 مجم سالازوبيرين sulfasalazine salazopyrin", unit: "قرص", purchasePrice: "1.91", nafqaPrice: "2.04", ahalyPrice: "3.35" },
  { category: "أقراص", name: "سينوبريل 5 مجم ليزينوبريل sinopril 5mg lisinopril", unit: "قرص", purchasePrice: "0.95", nafqaPrice: "1.01", ahalyPrice: "1" },
  { category: "أقراص", name: "سينوبريل كو ليزينوبريل مدر sinopril co zestoretic lisinopril hydrochlorothiazide", unit: "قرص", purchasePrice: "1.37", nafqaPrice: "1.46", ahalyPrice: "3.5" },
  { category: "أقراص", name: "سيلوكين زوك 50 مجم ميتوبرولول سوكسينات seloken zok 50mg betaloc metoprolol", unit: "قرص", purchasePrice: "2.77", nafqaPrice: "2.97", ahalyPrice: "3.36" },
  { category: "أقراص", name: "ريسبريدون 1مجم risperidone 1mg ريسبردال risperdal", unit: "قرص", purchasePrice: "1.01", nafqaPrice: "1.08", ahalyPrice: "3.05" },
  { category: "أقراص", name: "روزوفاستاتين 10 كوليروز rosuvastatin cholerose", unit: "قرص", purchasePrice: "0.83", nafqaPrice: "0.89", ahalyPrice: "3.5" },
  { category: "أقراص", name: "سيلدينافيل 50 مجم sildenafil فياجرا viagra", unit: "قرص", purchasePrice: "2.10", nafqaPrice: "2.25", ahalyPrice: "8.25" },
  { category: "أقراص", name: "فيبوكس ستات 80 FEBUXOSTAT فيبوريك feburoic", unit: "قرص", purchasePrice: "2.47", nafqaPrice: "2.64", ahalyPrice: "4.65" },
  { category: "أقراص", name: "فروسيميد 40 مجم frusemide لازيكس lasix", unit: "قرص", purchasePrice: "0.41", nafqaPrice: "0.44", ahalyPrice: "0.6" },
  { category: "أقراص", name: "فوليك اسيد mg5 folic acid", unit: "قرص", purchasePrice: "0.30", nafqaPrice: "0.33", ahalyPrice: "0.5" },
  { category: "أقراص", name: "كارفيد 6.25 كارفيديلول ديلاتريند carvid 6.25mg carvedilol dilatrend", unit: "قرص", purchasePrice: "0.45", nafqaPrice: "0.48", ahalyPrice: "1.5" },
  { category: "أقراص", name: "كارفيد 12.5 كارفيديلول ديلاتريند carvid 12.5mg carvedilol dilatrend", unit: "قرص", purchasePrice: "0.84", nafqaPrice: "0.90", ahalyPrice: "1.1" },
  { category: "أقراص", name: "كلوبيدوجريل 75 clopidogril بلافيكس plavix", unit: "قرص", purchasePrice: "9.60", nafqaPrice: "10.27", ahalyPrice: "11.1" },
  { category: "أقراص", name: "كلوبيدوجريل 75 مجم (مصري / بدائل) clopidogrel 75mg clopex myogrel", unit: "قرص", purchasePrice: "1.14", nafqaPrice: "1.22", ahalyPrice: "3.9" },
  { category: "أقراص", name: "كابتوبريل 25 مجم كابوتين captopril 25mg capoten", unit: "قرص", purchasePrice: "0.74", nafqaPrice: "0.79", ahalyPrice: "1" },
  { category: "أقراص", name: "كولشيسين 500 colchicine", unit: "قرص", purchasePrice: "1.38", nafqaPrice: "1.47", ahalyPrice: "1.9" },
  { category: "أقراص", name: "كاربيمازول carbimazole 5mg", unit: "قرص", purchasePrice: "0.96", nafqaPrice: "1.02", ahalyPrice: "1.1" },
  { category: "أقراص", name: "كاردورا 4 مجم دوكسازوسين cardura 4mg doxazosin", unit: "قرص", purchasePrice: "2.73", nafqaPrice: "2.92", ahalyPrice: "5.7" },
  { category: "أقراص", name: "كوزانتوكس أقراص cosantox cozantex", unit: "قرص", purchasePrice: "2.37", nafqaPrice: "2.54", ahalyPrice: "7.5" },
  { category: "أقراص", name: "ليفوفلوكساسين 750 تافانيك levofloxacin tavanic", unit: "قرص", purchasePrice: "3.62", nafqaPrice: "3.88", ahalyPrice: "8" },
  { category: "أقراص", name: "لازيلاكتون 50/20 سبيرونولاكتون فوروسيميد lasilactone 50/20 spironolactone furosemide", unit: "قرص", purchasePrice: "1.20", nafqaPrice: "1.28", ahalyPrice: "4.2" },
  { category: "أقراص", name: "ميتفورمين 1000 سيدوفاج metformin 1000 cidophage", unit: "قرص", purchasePrice: "1.31", nafqaPrice: "1.40", ahalyPrice: "2.35" },
  { category: "أقراص", name: "ميتفورمين 850 سيدوفاج metformin 850 cidophage glucophage", unit: "قرص", purchasePrice: "1.26", nafqaPrice: "1.35", ahalyPrice: "2.2" },
  { category: "أقراص", name: "مونتيلوكاست 10 مجم سينجولير ازماكاست montelukast 10mg singulair clairair asmacast", unit: "قرص", purchasePrice: "2.36", nafqaPrice: "2.53", ahalyPrice: "4" },
  { category: "أقراص", name: "ميثيل دوبا 250 مجم الدومت methyldopa 250mg aldomet", unit: "قرص", purchasePrice: "2.63", nafqaPrice: "2.81", ahalyPrice: "3.7" },
  { category: "أقراص", name: "مترونيدازول 500 فلاجيل metronidazole 500mg flagyl", unit: "قرص", purchasePrice: "0.79", nafqaPrice: "0.84", ahalyPrice: "1.15" },
  { category: "أقراص", name: "ميتاكارديا ميتاميدين 20 مجم تريميتازيدين فاستاريل trimetazidine 20mg vastarel metamidine metacardia", unit: "قرص", purchasePrice: "0.77", nafqaPrice: "0.82", ahalyPrice: "1.95" },
  { category: "أقراص", name: "مونوماك مونونيت 40 مجم ايزوسوربيد ايمدور isosorbide mononitrate 40 mononit imdur monomak", unit: "قرص", purchasePrice: "0.95", nafqaPrice: "1.01", ahalyPrice: "2.15" },
  { category: "أقراص", name: "موف ايزي سايكلوبنزابرين 10 مجم مالتي ريلاكس move easy cyclobenzaprine 10mg multi-relax moveasy", unit: "قرص", purchasePrice: "1.05", nafqaPrice: "1.12", ahalyPrice: "1.55" },
  { category: "أقراص", name: "ميلجا نيوروفيت فيتامين ب milga neurovit b complex", unit: "قرص", purchasePrice: "0.95", nafqaPrice: "1.01", ahalyPrice: "2.7" },
  { category: "أقراص", name: "ميكوستا أقراص ريباميبيد mucosta rebamipide", unit: "قرص", purchasePrice: "0.95", nafqaPrice: "1.01", ahalyPrice: "2.7" },
  { category: "أقراص", name: "ميثيل تكنو أفلام methyltechno b12", unit: "قرص", purchasePrice: "2.05", nafqaPrice: "2.19", ahalyPrice: "4.5" },
  { category: "أقراص", name: "ميجكس ريباجلينيد نوفونورم megix repaglinide novonorm", unit: "قرص", purchasePrice: "4.10", nafqaPrice: "4.38", ahalyPrice: "5.7" },
  { category: "أقراص", name: "ماريفان 3 مجم وارفارين marevan 3mg warfarin", unit: "قرص", purchasePrice: "-", nafqaPrice: "0.19", ahalyPrice: "0.36" },
  { category: "أقراص", name: "ماريفان 3 مجم وارفارين marevan 3mg warfarin", unit: "قرص", purchasePrice: "0.44", nafqaPrice: "0.47", ahalyPrice: "0.5" },
  { category: "أقراص", name: "ماريفان 5 مجم وارفارين 5 مجم warfarin 5mg marevan", unit: "قرص", purchasePrice: "0.44", nafqaPrice: "0.47", ahalyPrice: "0.5" },
  { category: "أقراص", name: "فورميترول فيومارات متروهيلر فوراديل formoterol fumarate metrohaler foradil", unit: "قرص", purchasePrice: "4.20", nafqaPrice: "4.49", ahalyPrice: "5.7" },
  { category: "أقراص", name: "نيتروجليسرين 2.5 مجم نيتروماك ريتارد nitroglycerin 2.5mg nitromak", unit: "قرص", purchasePrice: "0.84", nafqaPrice: "0.90", ahalyPrice: "1.6" },
  { category: "أقراص", name: "نيبفولول 5 مجم نيبيلت نيفيلوب nebivolol 5mg nebilet nevilob", unit: "قرص", purchasePrice: "1.84", nafqaPrice: "1.97", ahalyPrice: "4.7" },
  { category: "أقراص", name: "هيدروكسي كلوروكين بلاكونيل هيدروكين هيدروكسيكوين hydroxychloroquine sulphate plaquenil hydroquine hydroquin", unit: "قرص", purchasePrice: "3.05", nafqaPrice: "3.26", ahalyPrice: "4.1" },
  { category: "أقراص", name: "سريبروماب 200 مجم براكسيلان نافتيدروفوريل cerebromap 200mg praxilene naftidrofuryl", unit: "قرص", purchasePrice: "5.68", nafqaPrice: "6.08", ahalyPrice: "7.5" },
  { category: "أقراص", name: "فيلداجلبتن 50 مجم جالفوس فيلداجلوز vildagliptin 50mg galvus vildaglose", unit: "قرص", purchasePrice: "1.58", nafqaPrice: "1.69", ahalyPrice: "4.1" },
  { category: "أقراص", name: "فيلداجلبتن بلس 50/1000 جالفوس مت فيلداجلوز بلس vildagliptin 50mg + metformin 1000mg galvus met vildaglose plus", unit: "قرص", purchasePrice: "2.21", nafqaPrice: "2.36", ahalyPrice: "4.55" },
  { category: "أقراص", name: "فاموتيدين 40 مجم انتودين famotidine 40mg antodine", unit: "قرص", purchasePrice: "1.05", nafqaPrice: "1.12", ahalyPrice: "3" },
  { category: "أقراص", name: "فوريكونازول 200 مجم ففند voriconazole 200mg vfend", unit: "قرص", purchasePrice: "40.95", nafqaPrice: "43.82", ahalyPrice: "87.85" },
  { category: "أقراص", name: "فالسارتان 80 مجم تارج دايوفان valsartan 80mg tareg diovan disartan", unit: "قرص", purchasePrice: "1.37", nafqaPrice: "1.46", ahalyPrice: "3.3" },
  { category: "أقراص", name: "فلوكسيتين 80 مجم بروزاك فلوزاك fluoxetine 80mg prozac", unit: "قرص", purchasePrice: "1.37", nafqaPrice: "1.46", ahalyPrice: "3.3" },
  { category: "أقراص", name: "فيراباميل 80 مجم ايزوبتين verapamil 80mg isoptin", unit: "قرص", purchasePrice: "1.31", nafqaPrice: "1.40", ahalyPrice: "1.7" },
  { category: "أقراص", name: "فيتايامي كبسول vitayami multivitamins", unit: "قرص", purchasePrice: "1.49", nafqaPrice: "1.60", ahalyPrice: "4.5" },
  { category: "أقراص", name: "كالسيوم كربونات 600 مجم كالسيمات كال بريج calcium carbonate 600mg calcimate cal-preg calpreg", unit: "قرص", purchasePrice: "1.00", nafqaPrice: "1.07", ahalyPrice: "3.3" },
  { category: "أقراص", name: "هيدروكلوروثيازيد 12.5 مجم hydrochlorothiazide 12.5mg esidrex", unit: "قرص", purchasePrice: "2.10", nafqaPrice: "2.25", ahalyPrice: "5.3" },
  { category: "أقراص", name: "برومازيبام 1.5 مجم كالميبام لكسوتانيل bromazepam 1.5mg calmepam lexotanil", unit: "قرص", purchasePrice: "0.30", nafqaPrice: "0.32", ahalyPrice: "1" },
  { category: "أقراص", name: "ديجوكسين 0.25 مجم لانوكسين كارديكسين digoxin 0.25mg lanoxin cardixin", unit: "قرص", purchasePrice: "0.42", nafqaPrice: "0.45", ahalyPrice: "0.9" },
  { category: "أقراص", name: "رواتينكس كبسول يورينكس rowatinex urinex", unit: "قرص", purchasePrice: "0.87", nafqaPrice: "0.93", ahalyPrice: "1.16" },
  { category: "أقراص", name: "يونيكتام 375مجم أقراص (سلبوكتام + أمبيسيلين / Unictam 375mg / Ampicillin + Sulbactam)", unit: "قرص", purchasePrice: "3.15", nafqaPrice: "3.37", ahalyPrice: "7.5" },
  { category: "أقراص", name: "يونيكتام 750مجم أقراص (سلبوكتام + أمبيسيلين / Unictam 750mg / Ampicillin + Sulbactam)", unit: "قرص", purchasePrice: "6.30", nafqaPrice: "6.74", ahalyPrice: "15" },
  { category: "أقراص", name: "هيستافري فيكسوفينادين تلفاست fexofenadine histafree telfast", unit: "قرص", purchasePrice: "0.97", nafqaPrice: "1.03", ahalyPrice: "3.3" }
];
